name: extraer_conf

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
      - uses: actions/checkout@v4

      - name: Python setup
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
      - run: python ./
      
      
